import {
	type ProviderName,
	type ModelInfo,
	providerIdentifiers,
	anthropicModels,
	bedrockModels,
	deepSeekModels,
	moonshotModels,
	geminiModels,
	mistralModels,
	openAiNativeModels,
	openAiCodexModels,
	qwenCodeModels,
	vertexModels,
	xaiModels,
	sambaNovaModels,
	internationalZAiModels,
	fireworksModels,
	friendliModels,
	minimaxModels,
	basetenModels,
	mimoModels,
} from "@roo-code/types"

export const MODELS_BY_PROVIDER: Partial<Record<ProviderName, Record<string, ModelInfo>>> = {
	[providerIdentifiers.anthropic]: anthropicModels,
	[providerIdentifiers.bedrock]: bedrockModels,
	[providerIdentifiers.deepseek]: deepSeekModels,
	[providerIdentifiers.moonshot]: moonshotModels,
	[providerIdentifiers.gemini]: geminiModels,
	[providerIdentifiers.mistral]: mistralModels,
	[providerIdentifiers.openaiNative]: openAiNativeModels,
	[providerIdentifiers.openaiCodex]: openAiCodexModels,
	[providerIdentifiers.qwenCode]: qwenCodeModels,
	[providerIdentifiers.vertex]: vertexModels,
	[providerIdentifiers.xai]: xaiModels,
	[providerIdentifiers.sambanova]: sambaNovaModels,
	[providerIdentifiers.zai]: internationalZAiModels,
	[providerIdentifiers.fireworks]: fireworksModels,
	[providerIdentifiers.friendli]: friendliModels,
	[providerIdentifiers.minimax]: minimaxModels,
	[providerIdentifiers.mimo]: mimoModels,
	[providerIdentifiers.baseten]: basetenModels,
}

export const PROVIDERS: Array<{ value: string; label: string; proxy: boolean }> = [
	{ value: providerIdentifiers.openrouter, label: "OpenRouter", proxy: false },
	{ value: providerIdentifiers.anthropic, label: "Anthropic", proxy: false },
	{ value: providerIdentifiers.gemini, label: "Google Gemini", proxy: false },
	{ value: providerIdentifiers.deepseek, label: "DeepSeek", proxy: false },
	{ value: providerIdentifiers.moonshot, label: "Moonshot", proxy: false },
	{ value: providerIdentifiers.kimiCode, label: "Kimi Code", proxy: false },
	{ value: providerIdentifiers.openaiNative, label: "OpenAI", proxy: false },
	{ value: providerIdentifiers.openaiCodex, label: "OpenAI - ChatGPT Plus/Pro", proxy: false },
	{ value: providerIdentifiers.openai, label: "OpenAI Compatible", proxy: true },
	{ value: providerIdentifiers.qwenCode, label: "Qwen Code", proxy: false },
	{ value: providerIdentifiers.vertex, label: "GCP Vertex AI", proxy: false },
	{ value: providerIdentifiers.bedrock, label: "Amazon Bedrock", proxy: false },
	{ value: providerIdentifiers.vscodeLm, label: "VS Code LM API", proxy: false },
	{ value: providerIdentifiers.mistral, label: "Mistral", proxy: false },
	{ value: providerIdentifiers.lmstudio, label: "LM Studio", proxy: true },
	{ value: providerIdentifiers.ollama, label: "Ollama", proxy: true },
	{ value: providerIdentifiers.requesty, label: "Requesty", proxy: false },
	{ value: providerIdentifiers.xai, label: "xAI (Grok)", proxy: false },
	{ value: providerIdentifiers.litellm, label: "LiteLLM", proxy: true },
	{ value: providerIdentifiers.sambanova, label: "SambaNova", proxy: false },
	{ value: providerIdentifiers.zai, label: "Z.ai", proxy: false },
	{ value: providerIdentifiers.fireworks, label: "Fireworks AI", proxy: false },
	{ value: providerIdentifiers.friendli, label: "Friendli", proxy: false },
	{ value: providerIdentifiers.vercelAiGateway, label: "Vercel AI Gateway", proxy: false },
	{ value: providerIdentifiers.opencodeGo, label: "Opencode Go", proxy: false },
	{ value: providerIdentifiers.kenari, label: "Kenari", proxy: false },
	{ value: providerIdentifiers.nanogpt, label: "NanoGPT", proxy: false },
	{ value: providerIdentifiers.minimax, label: "MiniMax", proxy: false },
	{ value: providerIdentifiers.mimo, label: "Xiaomi MiMo", proxy: false },
	{ value: providerIdentifiers.baseten, label: "Baseten", proxy: false },
	{ value: providerIdentifiers.unbound, label: "Unbound", proxy: false },
	{ value: providerIdentifiers.poe, label: "Poe", proxy: false },
].sort((a, b) => a.label.localeCompare(b.label))
