// AUTO-GENERATED by scripts/generate-announcements.mjs — DO NOT EDIT.
// Regenerate with `pnpm generate:announcements`. Source of truth:
// src/CHANGELOG.md (top versioned section). Highlights are English-only,
// auto-derived from changeset summaries; non-English locales fall back to the
// translated chat:announcement.release.highlightN keys.
//
// LINE-KEYED RELEASE POLICY (iterate-then-stabilize, same minor): one
// announcement per MINOR LINE, keyed at the line base <major>.<minor>.0. Every
// patch on the line (pre-release patches and the stable patch alike) resolves
// to the line base at runtime via getAnnouncementForVersion, so the "What's
// New" popup shows the right highlights for any build without per-patch data.

/** Release highlights for a specific extension version (English-only). */
export interface ReleaseAnnouncement {
	version: string
	/** English-only, auto-generated from the current CHANGELOG section. */
	highlights: string[]
}

export const Announcements: Record<string, ReleaseAnnouncement> = {
	"3.87.0": {
		version: "3.87.0",
		highlights: [
			"🎉 Milestone one is a wrap — a stable release, 300+ modes, and a clear roadmap for the road ahead. We couldn't be more excited about what's next.",
			"🚀 Milestone two begins now — guided by your feedback, we're doubling down on building a local-first, agentic IDE extension that makes your AI spend legible and your knowledge portable.",
			"❤️ To our 7.6k active users — thank you for choosing Roo+ and sharing this milestone with us. We're honored to have you on board — and we can't wait for the journey ahead.",
		],
	},
}

/**
 * Resolves a full <major>.<minor>.<patch> version to its announcement LINE BASE
 * <major>.<minor>.0. Announcements are keyed once per minor line, so every patch
 * on a minor shares the line base's highlights. Versions without a third segment
 * cannot resolve and return undefined (no false positives).
 */
export function resolveLineVersion(version: string): string | undefined {
	const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(version)
	if (!match) {
		return undefined
	}
	return match[1] + "." + match[2] + ".0"
}

/**
 * Returns the announcement for a version, resolving any patch on a minor to the
 * line base <major>.<minor>.0. Exact matches win; a version without a third
 * segment (or a line with no content) returns undefined.
 */
export function getAnnouncementForVersion(version: string): ReleaseAnnouncement | undefined {
	const exact = Announcements[version]
	if (exact !== undefined) {
		return exact
	}
	const lineBase = resolveLineVersion(version)
	if (lineBase === undefined) {
		return undefined
	}
	return Announcements[lineBase]
}

/**
 * True when the given version has non-empty announcement content to show.
 * Used by the extension trigger so the popup only re-arms when the resolved
 * line actually has content (noise mitigation). Line-resolved: any patch on a
 * minor resolves to the line base.
 */
export function hasAnnouncementForVersion(version: string): boolean {
	const announcement = getAnnouncementForVersion(version)
	return announcement !== undefined && announcement.highlights.length > 0
}
