// AUTO-GENERATED by scripts/generate-announcements.mjs — DO NOT EDIT.
// Regenerate with `pnpm generate:announcements`. Source of truth:
// src/CHANGELOG.md (top versioned section). Highlights are English-only,
// auto-derived from changeset summaries; non-English locales fall back to the
// translated chat:announcement.release.highlightN keys.

/** Release highlights for a specific extension version (English-only). */
export interface ReleaseAnnouncement {
	version: string
	/** English-only, auto-generated from the current CHANGELOG section. */
	highlights: string[]
}

export const Announcements: Record<string, ReleaseAnnouncement> = {
	"3.86.0": {
		version: "3.86.0",
		highlights: [
			"🎉 Milestone one is a wrap — a stable release, 300+ modes, and a clear roadmap for the road ahead. We couldn't be more excited about what's next.",
			"🚀 Milestone two begins now — guided by your feedback, we're doubling down on building a local-first, agentic IDE extension that makes your AI spend legible and your knowledge portable.",
			"❤️ To our 5.2k active users — thank you for choosing Roo+ and sharing this milestone with us. We're honored to have you on board — and we can't wait for the journey ahead.",
		],
	},
}

/**
 * True when the given version has non-empty announcement content to show.
 * Used by the extension trigger so the popup only re-arms when there is real
 * per-version content (noise mitigation).
 */
export function hasAnnouncementForVersion(version: string): boolean {
	const announcement = Announcements[version]
	return announcement !== undefined && announcement.highlights.length > 0
}
