// AUTO-GENERATED by scripts/generate-announcements.mjs — DO NOT EDIT.
// Regenerate with `pnpm generate:announcements`. Source of truth:
// src/CHANGELOG.md (top versioned section). Highlights are English-only,
// auto-derived from changeset summaries; non-English locales fall back to the
// translated chat:announcement.release.highlightN keys.

/** Release highlights for a specific extension version (English-only). */
export interface ReleaseAnnouncement {
	version: string
	/** English-only, auto-generated from the current CHANGELOG section. */
	highlights: string[]
}

export const Announcements: Record<string, ReleaseAnnouncement> = {
	"3.81.0": {
		version: "3.81.0",
		highlights: [
			"Webview React #301 startup crash and seen-set churn resolved",
			"Render-phase `setState` loops eliminated",
			"Open VSX pre-release marker stamped into packaged manifest",
			"Pre-release publish fails loudly with notifications",
			"Stale release-governance docs and announcement visualization removed",
		],
	},
}

/**
 * True when the given version has non-empty announcement content to show.
 * Used by the extension trigger so the popup only re-arms when there is real
 * per-version content (noise mitigation).
 */
export function hasAnnouncementForVersion(version: string): boolean {
	const announcement = Announcements[version]
	return announcement !== undefined && announcement.highlights.length > 0
}
